[package]
name = "shared_lib"
version = "0.1.0"
edition = "2021"
dependencies.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }
